"""empty message

Revision ID: 06746d5f8bab
Revises: 
Create Date: 2020-01-08 14:43:14.661905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06746d5f8bab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Positions')
    op.drop_table('JobApplications')
    op.alter_column('Candidates', 'location',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Candidates', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Candidates', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Candidates', 'location',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('JobApplications',
    sa.Column('idCandidate', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idPosition', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idCandidate', 'idPosition', name='application_pkey')
    )
    op.create_table('Positions',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Position_pkey')
    )
    # ### end Alembic commands ###
